# Generated by Django 4.1.7 on 2023-05-30 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_auhtor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 30, 6, 34, 6, 5)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
